# Site settings
title: I'm Jac.in/ta
email: jaci.brunning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write code for people who write code for people who drive robots.
baseurl: "/ta"
url: "http://imjac.in" # the base hostname & protocol for your site
twitter_username: JacisNonsense
github_username:  JacisNonsense

paginate: 9
paginate_path: "/page/:num/"

permalink: "/post/:year/:month/:day/:title.html"
future: true

safe: false

excerpt_separator: '<!-- excerpt -->'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

destination: ../_build/html/ta/

plugins: ['jekyll-paginate']

#excerpt_separator: ""

exclude:
  - "*_DEMO"
  - "*_DISABLED"
